apiVersion: v1
kind: Secret
metadata:
  name: disaster-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/disaster"
  REDIS_URI: "redis://redis-service:6379"
  JWT_SECRET: "your_prod_secret"
